version: '3.6'
services:
  genesis:
    container_name: genesis
    build: ./nodes/genesis
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}
    ports:
      - '8888:8888'
      - '9876:9876'
      - '9879:9879'
    volumes:
      - ./contracts/phoenix-contracts/build/contracts:/eosio.contracts
      - ./contracts/staking-contract/build:/staking-contract
    working_dir: /app
    command: bash -c "./start.sh"
    environment:
      TESTNET_EOSIO_PRIVATE_KEY: '${TESTNET_EOSIO_PRIVATE_KEY}'
      TESTNET_EOSIO_PUBLIC_KEY: '${TESTNET_EOSIO_PUBLIC_KEY}'
  cryptobloksx:
    container_name: cryptobloksx
    build: ./nodes/cryptobloksx
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}2
    ports:
      - '8890:8888'
      - '9880:9876'
      - '9881:9879'
    working_dir: /opt/scripts
    command: bash -c "./start.sh"
    environment:
      TESTNET_NODE_PRIVATE_KEY: '${TESTNET_NODE_PRIVATE_KEY}'
      TESTNET_NODE_PUBLIC_KEY: '${TESTNET_NODE_PUBLIC_KEY}'
  edeniaedenia:
    container_name: edeniaedenia
    build: ./nodes/edeniaedenia
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}3
    ports:
      - '8891:8888'
      - '9882:9876'
      - '9883:9879'
    working_dir: /opt/scripts
    command: bash -c "./start.sh"
    environment:
      TESTNET_NODE2_PRIVATE_KEY: '${TESTNET_NODE2_PRIVATE_KEY}'
      TESTNET_NODE2_PUBLIC_KEY: '${TESTNET_NODE2_PUBLIC_KEY}'
  zenhash:
    container_name: zenhash
    build: ./nodes/zenhash
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}3
    ports:
      - '8892:8888'
      - '9884:9876'
      - '9885:9879'
    working_dir: /opt/scripts
    command: bash -c "./start.sh"
    environment:
      TESTNET_NODE3_PRIVATE_KEY: '${TESTNET_NODE3_PRIVATE_KEY}'
      TESTNET_NODE3_PUBLIC_KEY: '${TESTNET_NODE3_PUBLIC_KEY}'
  zuexeuz:
    container_name: zuexeuz
    build: ./nodes/zuexeuz
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}3
    ports:
      - '8893:8888'
      - '9886:9876'
      - '9887:9879'
    working_dir: /opt/scripts
    command: bash -c "./start.sh"
    environment:
      TESTNET_NODE4_PRIVATE_KEY: '${TESTNET_NODE4_PRIVATE_KEY}'
      TESTNET_NODE4_PUBLIC_KEY: '${TESTNET_NODE4_PUBLIC_KEY}'