version: '3.6'
services:
  blockchain:
    container_name: blockchain
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}
    ports:
      - '8888:8888'
    working_dir: /app
    command: bash -c "./start.sh"
    environment:
      TESTNET_EOSIO_PRIVATE_KEY: '${TESTNET_EOSIO_PRIVATE_KEY}'
      TESTNET_EOSIO_PUBLIC_KEY: '${TESTNET_EOSIO_PUBLIC_KEY}'