version: "3.8"
services:
  indexer:
    build: .
    # restart: on-failure
    volumes:
      - ./config/connections.json:/hyperion-history-api/connections.json
      - ./config/chains/:/hyperion-history-api/chains/
    networks:
      - libre-network
    command: ./run.sh local-indexer

  api:
    build: .
    ports:
      - "7000:7000"
    depends_on:
      - indexer
    volumes:
      - ./config/connections.json:/hyperion-history-api/connections.json
      - ./config/chains/:/hyperion-history-api/chains/
    networks:
      - libre-network
    command: ./run.sh local-api

networks:
  libre-network:
    external: true