name: Publish Docker image

on:
  push:
    branches: main

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            eoscostarica506/phoenix-local
            ghcr.io/${{ github.repository }}

      - name: Build new images and push
        run: |
          make \
            build-docker \
            push-image
        env:
          IMAGE_NAME: libre-node
          DOCKER_REGISTRY: eoscostarica506
          DEFAULT_PRIVATE_KEY: 5K11Z3fpvC6STquWJzgvHUjCyY7ya6JfwcuztcA9YS3QNKQAGds
          DEFAULT_PUBLIC_KEY: EOS4yhEJpSbQoLLUz6Y137wyXkRqfALRoGYUGywiLSEcDoyEaK9oC

          # Libre Network
          TESTNET_EOSIO_PRIVATE_KEY: 5JiiDeRyL85RH1RX6H8kV2dAYNXmjdRadH637J9zuJHcBhAUGuB
          TESTNET_EOSIO_PUBLIC_KEY: EOS7nGphuG3oNvED8hFTMdA9JRWFkHET2csURYbDdCJmhFfNpp9xZ

          # Libre Network - Node
          TESTNET_NODE_PRIVATE_KEY: 5KJ8PUffiGRKASSx5zZrDp7oNPqBJxqMtWfnKYtDm8ZaaVs3GeZ
          TESTNET_NODE_PUBLIC_KEY: EOS7ju8oBzd8uYFUdZzjcV4NvgPeXEvvBMtJYJcibrvGA4yPXfxcT

          # Libre Network - Node2
          TESTNET_NODE2_PRIVATE_KEY: 5JMpRkYwkh6PL8JqD8oUUnGTG6TVxawH8LpNGZJULDwbCG2eHgu
          TESTNET_NODE2_PUBLIC_KEY: EOS6GEtyTC1ophzGHFHRj5vZzgehPt7vPEGdDaCbtSg5qhzDLw7PE

          # Libre Network - Node3
          TESTNET_NODE3_PRIVATE_KEY: 5JhPLoPWsnduREjjPSWp53S2W9TY9ssj9yhwtRZGGZmetqvsWYf
          TESTNET_NODE3_PUBLIC_KEY: EOS6ThmAMojJ4wJ8jcnWTv6dGEu1462j5pXfXiqPZntbHftQtHKrz

          # Libre Network - Node4
          TESTNET_NODE4_PRIVATE_KEY: 5JJRKwDt5TFBmz3J9rC7XqNTVXmx2C3uMyaVr1NmfEorAenJNGk
          TESTNET_NODE4_PUBLIC_KEY: EOS5oUhfzC1RZipsSTieSxgiFQ5ZDkQMPDH2nD7YUeRNQkyBWSYb9
