name: Publish Docker image

on:
  push:
    branches: main

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          IMAGE_NAME: libre-node
          DOCKER_REGISTRY: ghcr.io/edenia/libre-local

          # Network
          INITIAL_CHAIN_ID: cfbedb8854d98ef23e614e66786f1ab69383c2d79699b030366d10de1c823be0
          DEFAULT_PRIVATE_KEY: 5K11Z3fpvC6STquWJzgvHUjCyY7ya6JfwcuztcA9YS3QNKQAGds
          DEFAULT_PUBLIC_KEY: EOS4yhEJpSbQoLLUz6Y137wyXkRqfALRoGYUGywiLSEcDoyEaK9oC

          # Libre Network
          TESTNET_EOSIO_PRIVATE_KEY: 5JiiDeRyL85RH1RX6H8kV2dAYNXmjdRadH637J9zuJHcBhAUGuB
          TESTNET_EOSIO_PUBLIC_KEY: EOS7nGphuG3oNvED8hFTMdA9JRWFkHET2csURYbDdCJmhFfNpp9xZ
